### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by homuraLan** [ttionya/picgo-plugin-lychee#1] opened 2023-08-27 08:34 UTC
Picgo V2.3 or V2.4.0 beta. 4 cannot be installed in Windows 11. After clicking on install, there is no response. I have already installed node

**Comment by homuraLan** [comment] 2023-08-27 08:41
I'm not sure if it's due to the internet, Picgo didn't give me any prompts, and after multiple attempts, it finally succeeded.

**Comment by ttionya** [comment] 2023-08-27 09:06
Unable to reproduce, perhaps as you mentioned, it's due to network issues.

I will close this issue. If you encounter any other problems while using it, feel free to provide feedback.

**Comment by homuraLan** [comment] 2023-08-27 13:07
> Unable to reproduce, perhaps as you mentioned, it's due to network issues.
> 
> I will close this issue. If you encounter any other problems while using it, feel free to provide feedback.

Like this, I used PicGO Core, although the prompt was successful, it doesn't seem to recognize it
```
SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\xxxxx\.picgo\node_modules\picgo-plugin-lychee\lib\index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
-------Error Stack End-------
2023-08-27 21:03:27 [PicGo ERROR] SyntaxError: Unexpected token '.'
------Error Stack Begin------
C:\Users\xxxxx\.picgo\node_modules\picgo-plugin-lychee\lib\uploader.js:36
        if (uploadedPhotoData.size_variants.original?.url) {
                                                     ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\xxxxx\.picgo\node_modules\picgo-plugin-lychee\lib\index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
-------Error Stack End-------
2023-08-27 21:03:27 [PicGo SUCCESS] 插件安装成功
```
![image](https://github.com/ttionya/picgo-plugin-lychee/assets/96775034/9b47c904-8059-49d3-9fa1-9449c0fbf3ab)
![image](https://github.com/ttionya/picgo-plugin-lychee/assets/96775034/c1624b2e-5196-4a31-9d7e-7b57dc636078)

**Comment by ttionya** [comment] 2023-08-27 15:46
What is your Node.js version?

PicGo-Core 1.5.0 and above recommend using Node.js version >=16.

> PicGo should be installed with node.js >= 12 (v1.5.0-alpha.4 and small) & node.js >= 16 (since v1.5.0-alpha.5).

**Comment by ttionya** [comment] 2023-08-27 16:28
I suspect your Node.js version doesn't meet the requirement of `>=16`, and I don't consider this to be a bug either.

However, I'm more than willing to make the code compatible with a wider range of Node.js versions. I've already released `v1.0.1`, so you can give it a try.

**Closed as completed by ttionya** 2023-08-27 16:28 UTC
Labels: enhancement

**Comment by homuraLan** [comment] 2023-08-27 18:48
> I suspect your Node.js version doesn't meet the requirement of `>=16`, and I don't consider this to be a bug either.
> 
> However, I'm more than willing to make the code compatible with a wider range of Node.js versions. I've already released `v1.0.1`, so you can give it a try.

![image](https://github.com/ttionya/picgo-plugin-lychee/assets/96775034/ba9aae25-c457-44b6-b635-c84ea37c3db3)

**Comment by ttionya** [comment] 2023-08-28 00:56
Typora's built-in PicGo-Core is packaged with Node.js v12.13 and PicGo-Core v1.4.7, which is below the required minimum version for the package. PicGo-Core 1.5.0 introduced new APIs, and this tool has been developed based on the new APIs introduced in version 1.5.0. I believe even version `v1.0.1` won't work properly.

I suggest you download the latest version of [PicGo-Core](https://github.com/PicGo/PicGo-Core) and use the `Custom Command` option in Typora to specify the latest version of PicGo-Core for your use.

**Comment by homuraLan** [comment] 2023-08-28 04:07
> Typora's built-in PicGo-Core is packaged with Node.js v12.13 and PicGo-Core v1.4.7, which is below the required minimum version for the package. PicGo-Core 1.5.0 introduced new APIs, and this tool has been developed based on the new APIs introduced in version 1.5.0. I believe even version `v1.0.1` won't work properly.
> 
> I suggest you download the latest version of [PicGo-Core](https://github.com/PicGo/PicGo-Core) and use the `Custom Command` option in Typora to specify the latest version of PicGo-Core for your use.

好，确实是这样，墓前一切正常

**Comment by homuraLan** [comment] 2023-08-28 04:20
> Typora's built-in PicGo-Core is packaged with Node.js v12.13 and PicGo-Core v1.4.7, which is below the required minimum version for the package. PicGo-Core 1.5.0 introduced new APIs, and this tool has been developed based on the new APIs introduced in version 1.5.0. I believe even version `v1.0.1` won't work properly.
> 
> I suggest you download the latest version of [PicGo-Core](https://github.com/PicGo/PicGo-Core) and use the `Custom Command` option in Typora to specify the latest version of PicGo-Core for your use.

![image](https://github.com/ttionya/picgo-plugin-lychee/assets/96775034/c5349274-9f94-4379-8f1b-79b09135fcba)

**Comment by homuraLan** [comment] 2023-08-28 04:40
> Typora's built-in PicGo-Core is packaged with Node.js v12.13 and PicGo-Core v1.4.7, which is below the required minimum version for the package. PicGo-Core 1.5.0 introduced new APIs, and this tool has been developed based on the new APIs introduced in version 1.5.0. I believe even version `v1.0.1` won't work properly.
> 
> I suggest you download the latest version of [PicGo-Core](https://github.com/PicGo/PicGo-Core) and use the `Custom Command` option in Typora to specify the latest version of PicGo-Core for your use.

莫非picgo也有内置的

> Typora's built-in PicGo-Core is packaged with Node.js v12.13 and PicGo-Core v1.4.7, which is below the required minimum version for the package. PicGo-Core 1.5.0 introduced new APIs, and this tool has been developed based on the new APIs introduced in version 1.5.0. I believe even version `v1.0.1` won't work properly.
> 
> I suggest you download the latest version of [PicGo-Core](https://github.com/PicGo/PicGo-Core) and use the `Custom Command` option in Typora to specify the latest version of PicGo-Core for your use.

UI版实测之后是1.0.1版本可以正常安装了之前的不知道
